language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - mkdir antsbin
  - cd antsbin
install: 
  - sudo apt-get install cmake
script: 
  - cmake ./.. && make && make test
