os:
  - linux
  - osx
language: cpp
compiler:
  #  - gcc it fails because of travis limited memory
  - clang
before_install:
  - sudo apt-get update
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.0-rc1-Linux-x86_64.sh
  - sudo sh cmake-3.2.0-rc1-Linux-x86_64.sh --skip-license --prefix=/usr
  - mkdir antsbin
  - cd antsbin
script:
  - cmake -DRUN_LONG_TESTS=OFF -DRUN_SHORT_TESTS=ON ./.. && make -j 2 && cd ANTS-build/ && make test
notifications:
  email:
    recipients:
      - arman.eshaghi@gmail.com
      - stnava@gmail.com
      - ntustison@gmail.com
