# .travis.yml using container-based infrastructure

language: cpp
compiler:
  - clang

# use containers
sudo: false

os:
  - linux
  - osx

before_install:
  - basedir=${PWD}
  - cd ..
  - if [[ $TRAVIS_OS_NAME -eq linux ]] ; wget http://www.cmake.org/files/v3.2/cmake-3.2.0-rc1-Linux-x86_64.sh ; sh cmake-3.2.0-rc1-Linux-x86_64.sh --skip-license --prefix=${HOME} ; fi
  - export PATH=$HOME/bin/:$PATH
  - cd $basedir
  - mkdir antsbin
  - cd antsbin

script:
  - cmake -DRUN_LONG_TESTS=OFF -DRUN_SHORT_TESTS=ON ./.. && make -j 2 && cd ANTS-build/ && make test

notifications:
  email:
    recipients:
      - arman.eshaghi@gmail.com
      - stnava@gmail.com
      - ntustison@gmail.com
