os:
  - linux
  - osx
language: cpp
compiler:
  #  - gcc it fails because of travis limited memory
  - clang
before_install:
  - sudo apt-get update
  - mkdir antsbin
  - cd antsbin
install:
  - sudo apt-get install -y cmake
script:
  - cmake -DRUN_LONG_TESTS=OFF -DRUN_SHORT_TESTS=ON ./.. && make -j 2 && cd ANTS-build/ && make test
notifications:
  email:
    recipients:
      - arman.eshaghi@gmail.com
      - stnava@gmail.com
      - ntustison@gmail.com
